# YAML

db:
    url: 'sqlite:///dev/db.sqlite'


system:
    wsgi:
        host: localhost
        port: 8080
    logger:
        level: DEBUG
        path: ./dev/logs/
        system: system.log
        app: app.log
        sql: sql.log
        view: view.log

