# YAML

db:
    url: 'sqlite:///dev/db.sqlite'

system:
    wsgi:
        host: localhost
        port: 8080
    logger:
        level: DEBUG
        handler_type: file
        path: ./dev/logs/
        filename: app.log
